from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate
from reportlab.platypus import Paragraph
from reportlab.platypus import Spacer


def generate_pdf(info, analysis, suggestions, output_path):

    styles = getSampleStyleSheet()

    doc = SimpleDocTemplate(output_path)

    story = []

    story.append(
        Paragraph("<b>CareerTwin AI Career Report</b>", styles["Title"])
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph("<b>Candidate Information</b>", styles["Heading2"])
    )

    story.append(
        Paragraph(f"Name: {info.get('name', 'N/A')}", styles["BodyText"])
    )

    story.append(
        Paragraph(f"Email: {info.get('email', 'N/A')}", styles["BodyText"])
    )

    story.append(
        Paragraph(f"Phone: {info.get('phone', 'N/A')}", styles["BodyText"])
    )

    story.append(
        Paragraph(f"GitHub: {info.get('github', 'N/A')}", styles["BodyText"])
    )

    story.append(
        Paragraph(f"LinkedIn: {info.get('linkedin', 'N/A')}", styles["BodyText"])
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph("<b>Resume Analysis</b>", styles["Heading2"])
    )

    story.append(
        Paragraph(f"ATS Score: {analysis['score']}%", styles["BodyText"])
    )

    story.append(
        Paragraph(f"Career Status: {analysis['readiness']}", styles["BodyText"])
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph("<b>Matched Skills</b>", styles["Heading2"])
    )

    for skill in analysis["matched"]:

        story.append(
            Paragraph(f"• {skill}", styles["BodyText"])
        )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph("<b>Missing Skills</b>", styles["Heading2"])
    )

    for skill in analysis["missing"]:

        story.append(
            Paragraph(f"• {skill}", styles["BodyText"])
        )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph("<b>Recommended Project</b>", styles["Heading2"])
    )

    story.append(
        Paragraph(
            suggestions["project"],
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "Generated by CareerTwin AI",
            styles["Italic"]
        )
    )

    doc.build(story)