from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import HexColor
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
)


def heading(text, styles):

    style = styles["Heading2"]

    style.textColor = HexColor("#2563EB")

    return Paragraph(text, style)


def body(text, styles):

    return Paragraph(text, styles["BodyText"])


def generate_pdf(
    info,
    analysis,
    suggestions,
    output_path
):

    styles = getSampleStyleSheet()

    title = styles["Title"]

    title.alignment = TA_CENTER

    title.textColor = HexColor("#1D4ED8")

    doc = SimpleDocTemplate(output_path)

    story = []

    # --------------------------------------------------
    # Title
    # --------------------------------------------------

    story.append(
        Paragraph(
            "CareerTwin AI Professional Career Report",
            title
        )
    )

    story.append(
        Spacer(1, 25)
    )

    # --------------------------------------------------
    # Candidate
    # --------------------------------------------------

    story.append(
        heading("Candidate Information", styles)
    )

    story.append(
        body(f"Name : {info.get('name','N/A')}", styles)
    )

    story.append(
        body(f"Email : {info.get('email','N/A')}", styles)
    )

    story.append(
        body(f"Phone : {info.get('phone','N/A')}", styles)
    )

    story.append(
        body(f"GitHub : {info.get('github','N/A')}", styles)
    )

    story.append(
        body(f"LinkedIn : {info.get('linkedin','N/A')}", styles)
    )

    story.append(
        Spacer(1,20)
    )

    # --------------------------------------------------
    # Resume Score
    # --------------------------------------------------

    story.append(
        heading("Resume Analysis", styles)
    )

    story.append(
        body(
            f"ATS Score : {analysis['score']}%",
            styles
        )
    )

    story.append(
        body(
            f"Career Status : {analysis['readiness']}",
            styles
        )
    )

    story.append(
        Spacer(1,20)
    )

    # --------------------------------------------------
    # Skills
    # --------------------------------------------------

    story.append(
        heading("Matched Skills", styles)
    )

    for skill in analysis["matched"]:

        story.append(
            body(f"• {skill}", styles)
        )

    story.append(
        Spacer(1,15)
    )

    story.append(
        heading("Missing Skills", styles)
    )

    for skill in analysis["missing"]:

        story.append(
            body(f"• {skill}", styles)
        )

    story.append(
        Spacer(1,20)
    )

    # --------------------------------------------------
    # AI Suggestions
    # --------------------------------------------------

    story.append(
        heading("AI Resume Suggestions", styles)
    )

    for item in suggestions["suggestions"]:

        story.append(
            body(
                f"• {item['title']} ({item['priority']})",
                styles
            )
        )

    story.append(
        Spacer(1,20)
    )

    # --------------------------------------------------
    # Recommended Project
    # --------------------------------------------------

    story.append(
        heading("Recommended Project", styles)
    )

    story.append(
        body(
            suggestions["project"],
            styles
        )
    )

    story.append(
        Spacer(1,30)
    )

    story.append(
        Paragraph(
            "<b>Generated by CareerTwin AI v2.1</b>",
            styles["Italic"]
        )
    )

    doc.build(story)